name: CI Pipeline

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v1

    - name: Install Qt Visual Studio Tools Extension
      shell: pwsh
      run: |
        $vsixPath = "$env:USERPROFILE\vsaddin-msvc2022.vsix"
        $vsixInstallerPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe"
        if (-Not (Test-Path $vsixInstallerPath)) {
          $vsixInstallerPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe"
        }
        if (-Not (Test-Path $vsixInstallerPath)) {
          throw "VSIXInstaller.exe not found."
        }
        & $vsixInstallerPath /quiet /a /q $vsixPath

    - name: Verify installation
      shell: pwsh
      run: |
        $devenvPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"
        if (-Not (Test-Path $devenvPath)) {
          $devenvPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"
        }
        if (-Not (Test-Path $devenvPath)) {
          throw "devenv.exe not found."
        }
        & $devenvPath /updateconfiguration
