name: CI Pipeline

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1


    - name: Install vswhere
      run: choco install vswhere

    - name: Download Qt 5.15.9
      run: |
        curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.9/qt-opensource-windows-x86-5.15.9.exe

    - name: Install Qt 5.15.9
      run: |
        qt-opensource-windows-x86-5.15.9.exe /silent

    - name: Clone Qt Visual Studio Tools
      run: git clone https://code.qt.io/qt-labs/vstools.git

    - name: Set environment variables
      run: |
        echo "QTBUILD_STATIC_VS2022=C:\\Qt\\5.15.9\\msvc2019_64" >> $GITHUB_ENV

    - name: Build Qt Visual Studio Tools
      run: |
        cd vstools
        vstools.bat -init -startvs

    - name: Verify installation
      run: |
        vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe

    - name: List Visual Studio Extensions
      run: |
        powershell -command "Get-ChildItem -Path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions'"

    - name: Check installation
      run: |
        powershell -command "Get-ChildItem -Path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions' | Where-Object { $_.Name -like '*Qt*' }"

