name: CI Pipeline

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.76.0
        override: true

    - name: Install Winget
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2091-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
        Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

    - name: Install Visual Studio 2022
      run: |
        winget install -e --id Microsoft.VisualStudio.2022.Community --source winget
        "C:\Program Files\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang --add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions --add Component.Qt.Qt5

    - name: Install Qt Visual Studio Tools
      run: |
        winget install -e --id TheQtCompany.QtVisualStudioTools --source winget
        
    - name: Build OpenTwin
      run: |
        cd ${{ github.workspace }}\MasterBuild
        buildAll.bat

    - name: Check Build Logs
      run: |
        type ${{ github.workspace }}\MasterBuild\buildLog_Summary.txt

    - name: Create Deployment
      run: |
        cd ${{ github.workspace }}\MasterBuild
        createDeployment.bat
