name: Install Qt Visual Studio Tools Extension

on: [push, pull_request]

jobs:
  setup-qt-vs-tools:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022 and Qt extension
      run: |
        choco install visualstudio2022buildtools --yes --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core"
        choco install qtcreator --yes

    - name: Setup Qt environment
      run: |
        echo "Setting up Qt environment variables"
        $qtPath = (Get-Command qtcreator).Path
        $qtDir = Split-Path $qtPath
        echo "QT_DIR=$qtDir" >> $env:GITHUB_ENV
        echo "QT_PLUGIN_PATH=$qtDir/plugins" >> $env:GITHUB_ENV
        echo "QT_QPA_PLATFORM_PLUGIN_PATH=$qtDir/plugins/platforms" >> $env:GITHUB_ENV
        echo "QT_BINARY_PATH=$qtDir/bin" >> $env:GITHUB_ENV
        echo "$qtDir/bin" >> $env:GITHUB_PATH

    - name: Install dependencies
      run: choco install cmake --yes

    - name: Build
      run: cmake --build .
