name: CI Pipeline

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.76.0
        override: true

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Qt Extension for Visual Studio
      run: |
        choco install qt-vs-tools --pre

    - name: Set Environment Variables
      run: |
        echo "DEVENV_ROOT_2022=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE" >> $GITHUB_ENV
        echo "OPENTWIN_DEV_ROOT=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Build OpenTwin
      run: |
        cd ${{ github.workspace }}\MasterBuild
        buildAll.bat

    - name: Check Build Logs
      run: |
        type ${{ github.workspace }}\MasterBuild\buildLog_Summary.txt

    - name: Create Deployment
      run: |
        cd ${{ github.workspace }}\MasterBuild
        createDeployment.bat
